### ISSUE TITLE
What LCD is this? and the Driver Chip?

### ISSUE THREAD

**Issue by Helder1981** [FunKey-Project/FunKey-S-Hardware#1]
This looks like a custom made LCD or a standard LCD with custom Flex on it. Can you tell us what the original LCD was or the driver IC it uses so other LCDs can be used.

Thanks.

**Comment by Michel-FK** [comment]
The original screen we used is a SAEF SF-TC154B-8377A-N which used to be available on Alibaba, but this is no longer the case.

You can find its datasheet here:
[ALIBABA_SAEF_SF-TC154B-8377A-N_annote.pdf](https://github.com/FunKey-Project/FunKey-S-Hardware/files/6016273/ALIBABA_SAEF_SF-TC154B-8377A-N_annote.pdf)

It uses an ST7789V integrated driver IC.

Our current screen is no longer manufactured by SAEF, but our changes to the orignal model are:

- change the flex shape and dimensions
- add the TE (Tearing Effect) signal from the driver IC on the connector (pin 9)

Here is our current screen spec:
[DISPLAY - SF-TC154B-8737A-N - CUSTOM FLEX - 0.3.PDF](https://github.com/FunKey-Project/FunKey-S-Hardware/blob/master/Datasheets/DISPLAY%20-%20SF-TC154B-8737A-N%20-%20CUSTOM%20FLEX%20-%200.3.PDF)
