### ISSUE TITLE
hiya -  is this project actually open source?

### ISSUE THREAD

**Issue by ladyada** [FunKey-Project/FunKey-S-Hardware#3]
hi there, on the kickstarter page and hackaday page (https://hackaday.io/project/164934/logs) describing this product is the text

"Since its [origins](https://www.funkey-project.com/), the FunKey S has proudly been Open Hardware & Open Source."

with the open source hardware logo and OSI logo:

![image](https://user-images.githubusercontent.com/1214161/152626954-3db0a481-36df-4b47-a33a-b4c3add16b91.png)

which is awesome! the open source hardware association, whose 'gear' logo is used on that page
https://www.oshwa.org/open-source-hardware-logo/
says
"This logo may be used if your hardware complies with the [Open Source Hardware Definition](https://www.oshwa.org/definition/)."
The definition at https://www.oshwa.org/definition/ specifies that you cannot have 'non commercial' as a restriction on the license.

This repository has a "Non Commercial" license tag.
![image](https://user-images.githubusercontent.com/1214161/152627051-c8a2ee83-0e7f-4a69-97bf-1addc5d2b92c.png)

please clarify: 

- if this is open hardware and if so, please update the license so it matches the requirements of using the open hardware logo and description. 
- or if it not open hardware, you cannot use the logo and must update the hackaday, kickstarter page, etc.

thank you :)

**Comment by ladyada** [comment]
hiya @squonk42 @Michel-FK @Vincent-FK please look at this issue and reply!

**Comment by ladyada** [comment]
also found on the wiki, another place that is not correct:

https://wiki.funkey-project.com/wiki/FunKey_Wiki_Knowledge_Center#What_is_the_FunKey_S?

```
Where can I find FunKey S device schematics and 3D files?

The FunKey Team has FunKey S schematics, STL files, and a project STEP file for the device's shell components available on [Grabcad](https://grabcad.com/library/funkey-s-1). Schematics for the device's electrical components are available on the FunKey Team's [GitHub page](https://github.com/FunKey-Project/FunKey-S-Hardware). As the device's hardware is open source, users are free to download, modify, and redistribute the listed files.
```

**Comment by Vincent-FK** [comment]
Hi @ladyada, 

Since it's our first product I must admit we're still tiptoeing around all the legal details so thanks a lot for your input, it's been corrected. 

Oh and btw, it goes without saying but still: thanks for Adafruit! Without it Keymu would never have been prototyped, which by extension means the FunKey S would not be there either.

**Comment by ladyada** [comment]
thats wonderful - thank you so much for updating the license. im really enjoying my funkey now EVEN MORE SO! :)
